variables:
  GIT_REVISION: TESTING123

steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', '$GIT_REVISION', '-t', 'us.gcr.io/dota-true-sight/website', '.']

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/dota-true-sight/website']

# Restart instance
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  timeout: 240s
  args: ['compute', 'instances', 'reset', 'website', '--zone=us-central1-a']

options:
  logging: CLOUD_LOGGING_ONLY
